### ISSUE TITLE
Soft reset hangs the Adafruit ItsyBitsy nRF52840 Express board.

### ISSUE THREAD

**Issue by gotfredsen** [adafruit/Adafruit_LTR390#2]
- Arduino board:  **Adafruit ItsyBitsy nRF52840 Express**
- Arduino IDE version: **1.8.15** 
- Steps to reproduce the problem:
1. Connect the LTR390 using I2C to the Adafruit ItsyBitsy nRF52840 Express
2. Run this example sketch.
3. Hangs when soft reset is executed.
4. Operates when soft reset is commented out. (Line 59-61 in Adafruit_LTR390.cpp)

```
  // OK now we can do a soft reset
  if (!reset()) {
    return false;
  }
```
Notes:
- Also tested on an ESP32 dev board, and here soft reset works, so one could argue it is a Adafruit ItsyBitsy nRF52840 Express problem, but that board has worked with plenty other I2C sensors.
- I have NOT used the LTR390 board from Adafruit, but another board with same sensor. That however works with this library on a non-Adafruit ESP32 dev board, ... and with the Adafruit ItsyBitsy nRF52840 Express, with the soft reset commented out.

**Comment by ladyada** [comment]
hmm yeah its some Wire core thing, its because the chip doesn't ack (because we just put it into reset) and it kinda freaks out
@hathach can take a look - for now please just remove that line

**Comment by hathach** [comment]
Please be patient, it may take a while for me to order an get my hands on LTR390 to test with.

**Comment by metanav** [comment]
I am having similar issue on the MacroPad RP2040 Starter Kit. Commenting out the code below works though.
```
 if (!reset()) {
    return false;
 }
```

**Comment by caternuson** [comment]
Related:
https://forums.adafruit.com/viewtopic.php?f=19&t=184853

Another RP2040 case. Can replicate issue locally. So not just an nRF core issue.

**Comment by caternuson** [comment]
There's the odd missing ACK behavior after sending the reset bit on a Raspberry Pi Pico (RP2040):
![image](https://user-images.githubusercontent.com/8755041/140425528-4b016622-2608-43eb-ab3f-8853f479c747.png)

And then 10ms later, the attempt to read it back:
![image](https://user-images.githubusercontent.com/8755041/140425584-f6777019-e68c-4390-8912-8fe9b13ce59c.png)

Starts OK, but then SCL hangs. So seems like I2C bus gets in a weird state.

**Comment by caternuson** [comment]
Simply trying again seems to work. But there's a ~1 second clock-strech-like delay between the two attempts:
```cpp
  if (softreset.read()) {
    if (softreset.read()) {
    return false;
    }
  }
```
![image](https://user-images.githubusercontent.com/8755041/140426751-7283fd99-66b8-475a-b86e-87cc681e5b53.png)

**Comment by caternuson** [comment]
Same trick does not work on Itsy nRF52840 :(

After the missing ACK/NACK, there's no more I2C traffic at all.

(zoomed in on last xfer with missing ACK/NACK):
![image](https://user-images.githubusercontent.com/8755041/140430016-e031c96d-e6ab-4a75-aabf-d9f79ff50e88.png)

(same trace zoomed out)
![image](https://user-images.githubusercontent.com/8755041/140430078-3f3b80ff-9f0c-4bbe-9c5d-7f2a501e29a4.png)

**Comment by hathach** [comment]
This issue is fixed, you need to update following core/libraries
- nRF52 core to 1.2.0
- Adafruit_LTR390 to 1.1.0
- Adafruit_BusIO to 1.9.8
