### ISSUE TITLE
UV index measurement question

### ISSUE THREAD

**Issue by szerwi** [adafruit/Adafruit_LTR390#5]
Hi,

Is this sensor suitable for outdoor UV index measurement?
I am using formulas from the datasheet to calculate Lux and UVI, but UVI readings  are very unstable.

On recommended settings for UV measurement (gain 18, resolution 20) the sensor shows 0.00 UVI during sunny day.
When  I lower the gain, it starts showing some data, but the measurements are very unstable (UVI can fluctuate from 0.00 to 2.00 when conditions are stable).

Have you tried to measure outdoor UV index using this sensor?

**Comment by ladyada** [comment]
this isnt a UV index sensor, so while it could be used for outdoor UV sensing it isn't calibrated for index output

**Comment by szerwi** [comment]
In the datasheet there is a UVI conversion formula: https://optoelectronics.liteon.com/upload/download/DS86-2015-0004/LTR-390UV_Final_%20DS_V1%201.pdf#page=24 (page 24)

So the manufacturer provides the formula, but it is still not calibrated for UVI measurement?

**Comment by ladyada** [comment]
you'd have to ask liteon to be sure - we make a functional breakout but we don't have any insight into how the sensor works on the inside - that's their intellectual propertly
